//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EYB.Web.SerialNumber {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCondition", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EYB.Web.SerialNumber.SerialNumberEntity))]
    public partial class BaseCondition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SidxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SordField;
        
        private int PageField;
        
        private int RowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIDField;
        
        private bool IsQueryField;
        
        private int pageNumField;
        
        private int numPerPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sidx {
            get {
                return this.SidxField;
            }
            set {
                if ((object.ReferenceEquals(this.SidxField, value) != true)) {
                    this.SidxField = value;
                    this.RaisePropertyChanged("Sidx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sord {
            get {
                return this.SordField;
            }
            set {
                if ((object.ReferenceEquals(this.SordField, value) != true)) {
                    this.SordField = value;
                    this.RaisePropertyChanged("Sord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((this.RowsField.Equals(value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIDField, value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsQuery {
            get {
                return this.IsQueryField;
            }
            set {
                if ((this.IsQueryField.Equals(value) != true)) {
                    this.IsQueryField = value;
                    this.RaisePropertyChanged("IsQuery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int pageNum {
            get {
                return this.pageNumField;
            }
            set {
                if ((this.pageNumField.Equals(value) != true)) {
                    this.pageNumField = value;
                    this.RaisePropertyChanged("pageNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int numPerPage {
            get {
                return this.numPerPageField;
            }
            set {
                if ((this.numPerPageField.Equals(value) != true)) {
                    this.numPerPageField = value;
                    this.RaisePropertyChanged("numPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string orderField {
            get {
                return this.orderFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.orderFieldField, value) != true)) {
                    this.orderFieldField = value;
                    this.RaisePropertyChanged("orderField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string orderDirection {
            get {
                return this.orderDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.orderDirectionField, value) != true)) {
                    this.orderDirectionField = value;
                    this.RaisePropertyChanged("orderDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ids {
            get {
                return this.idsField;
            }
            set {
                if ((object.ReferenceEquals(this.idsField, value) != true)) {
                    this.idsField = value;
                    this.RaisePropertyChanged("ids");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialNumberEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SerialNumberEntity : EYB.Web.SerialNumber.BaseCondition {
        
        private int IDField;
        
        private int HospitalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HospitalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        private int IsUseField;
        
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNumberField;
        
        private int NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int HospitalID {
            get {
                return this.HospitalIDField;
            }
            set {
                if ((this.HospitalIDField.Equals(value) != true)) {
                    this.HospitalIDField = value;
                    this.RaisePropertyChanged("HospitalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HospitalName {
            get {
                return this.HospitalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HospitalNameField, value) != true)) {
                    this.HospitalNameField = value;
                    this.RaisePropertyChanged("HospitalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int IsUse {
            get {
                return this.IsUseField;
            }
            set {
                if ((this.IsUseField.Equals(value) != true)) {
                    this.IsUseField = value;
                    this.RaisePropertyChanged("IsUse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MachineNumber {
            get {
                return this.MachineNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNumberField, value) != true)) {
                    this.MachineNumberField = value;
                    this.RaisePropertyChanged("MachineNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SerialNumber.SerialNumberSoap")]
    public interface SerialNumberSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 serialnumber 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEntityByserialnumber", ReplyAction="*")]
        EYB.Web.SerialNumber.GetEntityByserialnumberResponse GetEntityByserialnumber(EYB.Web.SerialNumber.GetEntityByserialnumberRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 MachineNumber 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEntityByMachineNumber", ReplyAction="*")]
        EYB.Web.SerialNumber.GetEntityByMachineNumberResponse GetEntityByMachineNumber(EYB.Web.SerialNumber.GetEntityByMachineNumberRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 serialnumber 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateByserialnumber", ReplyAction="*")]
        EYB.Web.SerialNumber.UpdateByserialnumberResponse UpdateByserialnumber(EYB.Web.SerialNumber.UpdateByserialnumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersion", ReplyAction="*")]
        double GetVersion(int type);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ip 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAppStatistics", ReplyAction="*")]
        EYB.Web.SerialNumber.AddAppStatisticsResponse AddAppStatistics(EYB.Web.SerialNumber.AddAppStatisticsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEntityByserialnumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEntityByserialnumber", Namespace="http://tempuri.org/", Order=0)]
        public EYB.Web.SerialNumber.GetEntityByserialnumberRequestBody Body;
        
        public GetEntityByserialnumberRequest() {
        }
        
        public GetEntityByserialnumberRequest(EYB.Web.SerialNumber.GetEntityByserialnumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEntityByserialnumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serialnumber;
        
        public GetEntityByserialnumberRequestBody() {
        }
        
        public GetEntityByserialnumberRequestBody(string serialnumber) {
            this.serialnumber = serialnumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEntityByserialnumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEntityByserialnumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public EYB.Web.SerialNumber.GetEntityByserialnumberResponseBody Body;
        
        public GetEntityByserialnumberResponse() {
        }
        
        public GetEntityByserialnumberResponse(EYB.Web.SerialNumber.GetEntityByserialnumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEntityByserialnumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EYB.Web.SerialNumber.SerialNumberEntity GetEntityByserialnumberResult;
        
        public GetEntityByserialnumberResponseBody() {
        }
        
        public GetEntityByserialnumberResponseBody(EYB.Web.SerialNumber.SerialNumberEntity GetEntityByserialnumberResult) {
            this.GetEntityByserialnumberResult = GetEntityByserialnumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEntityByMachineNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEntityByMachineNumber", Namespace="http://tempuri.org/", Order=0)]
        public EYB.Web.SerialNumber.GetEntityByMachineNumberRequestBody Body;
        
        public GetEntityByMachineNumberRequest() {
        }
        
        public GetEntityByMachineNumberRequest(EYB.Web.SerialNumber.GetEntityByMachineNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEntityByMachineNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MachineNumber;
        
        public GetEntityByMachineNumberRequestBody() {
        }
        
        public GetEntityByMachineNumberRequestBody(string MachineNumber) {
            this.MachineNumber = MachineNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEntityByMachineNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEntityByMachineNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public EYB.Web.SerialNumber.GetEntityByMachineNumberResponseBody Body;
        
        public GetEntityByMachineNumberResponse() {
        }
        
        public GetEntityByMachineNumberResponse(EYB.Web.SerialNumber.GetEntityByMachineNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEntityByMachineNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EYB.Web.SerialNumber.SerialNumberEntity GetEntityByMachineNumberResult;
        
        public GetEntityByMachineNumberResponseBody() {
        }
        
        public GetEntityByMachineNumberResponseBody(EYB.Web.SerialNumber.SerialNumberEntity GetEntityByMachineNumberResult) {
            this.GetEntityByMachineNumberResult = GetEntityByMachineNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateByserialnumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateByserialnumber", Namespace="http://tempuri.org/", Order=0)]
        public EYB.Web.SerialNumber.UpdateByserialnumberRequestBody Body;
        
        public UpdateByserialnumberRequest() {
        }
        
        public UpdateByserialnumberRequest(EYB.Web.SerialNumber.UpdateByserialnumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateByserialnumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serialnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MachineNumber;
        
        public UpdateByserialnumberRequestBody() {
        }
        
        public UpdateByserialnumberRequestBody(string serialnumber, string MachineNumber) {
            this.serialnumber = serialnumber;
            this.MachineNumber = MachineNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateByserialnumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateByserialnumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public EYB.Web.SerialNumber.UpdateByserialnumberResponseBody Body;
        
        public UpdateByserialnumberResponse() {
        }
        
        public UpdateByserialnumberResponse(EYB.Web.SerialNumber.UpdateByserialnumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateByserialnumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateByserialnumberResult;
        
        public UpdateByserialnumberResponseBody() {
        }
        
        public UpdateByserialnumberResponseBody(int UpdateByserialnumberResult) {
            this.UpdateByserialnumberResult = UpdateByserialnumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAppStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAppStatistics", Namespace="http://tempuri.org/", Order=0)]
        public EYB.Web.SerialNumber.AddAppStatisticsRequestBody Body;
        
        public AddAppStatisticsRequest() {
        }
        
        public AddAppStatisticsRequest(EYB.Web.SerialNumber.AddAppStatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAppStatisticsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IPAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime CreateTime;
        
        public AddAppStatisticsRequestBody() {
        }
        
        public AddAppStatisticsRequestBody(string ip, string IPAddress, System.DateTime CreateTime) {
            this.ip = ip;
            this.IPAddress = IPAddress;
            this.CreateTime = CreateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAppStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAppStatisticsResponse", Namespace="http://tempuri.org/", Order=0)]
        public EYB.Web.SerialNumber.AddAppStatisticsResponseBody Body;
        
        public AddAppStatisticsResponse() {
        }
        
        public AddAppStatisticsResponse(EYB.Web.SerialNumber.AddAppStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAppStatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddAppStatisticsResult;
        
        public AddAppStatisticsResponseBody() {
        }
        
        public AddAppStatisticsResponseBody(int AddAppStatisticsResult) {
            this.AddAppStatisticsResult = AddAppStatisticsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SerialNumberSoapChannel : EYB.Web.SerialNumber.SerialNumberSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerialNumberSoapClient : System.ServiceModel.ClientBase<EYB.Web.SerialNumber.SerialNumberSoap>, EYB.Web.SerialNumber.SerialNumberSoap {
        
        public SerialNumberSoapClient() {
        }
        
        public SerialNumberSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerialNumberSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerialNumberSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerialNumberSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EYB.Web.SerialNumber.GetEntityByserialnumberResponse EYB.Web.SerialNumber.SerialNumberSoap.GetEntityByserialnumber(EYB.Web.SerialNumber.GetEntityByserialnumberRequest request) {
            return base.Channel.GetEntityByserialnumber(request);
        }
        
        public EYB.Web.SerialNumber.SerialNumberEntity GetEntityByserialnumber(string serialnumber) {
            EYB.Web.SerialNumber.GetEntityByserialnumberRequest inValue = new EYB.Web.SerialNumber.GetEntityByserialnumberRequest();
            inValue.Body = new EYB.Web.SerialNumber.GetEntityByserialnumberRequestBody();
            inValue.Body.serialnumber = serialnumber;
            EYB.Web.SerialNumber.GetEntityByserialnumberResponse retVal = ((EYB.Web.SerialNumber.SerialNumberSoap)(this)).GetEntityByserialnumber(inValue);
            return retVal.Body.GetEntityByserialnumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EYB.Web.SerialNumber.GetEntityByMachineNumberResponse EYB.Web.SerialNumber.SerialNumberSoap.GetEntityByMachineNumber(EYB.Web.SerialNumber.GetEntityByMachineNumberRequest request) {
            return base.Channel.GetEntityByMachineNumber(request);
        }
        
        public EYB.Web.SerialNumber.SerialNumberEntity GetEntityByMachineNumber(string MachineNumber) {
            EYB.Web.SerialNumber.GetEntityByMachineNumberRequest inValue = new EYB.Web.SerialNumber.GetEntityByMachineNumberRequest();
            inValue.Body = new EYB.Web.SerialNumber.GetEntityByMachineNumberRequestBody();
            inValue.Body.MachineNumber = MachineNumber;
            EYB.Web.SerialNumber.GetEntityByMachineNumberResponse retVal = ((EYB.Web.SerialNumber.SerialNumberSoap)(this)).GetEntityByMachineNumber(inValue);
            return retVal.Body.GetEntityByMachineNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EYB.Web.SerialNumber.UpdateByserialnumberResponse EYB.Web.SerialNumber.SerialNumberSoap.UpdateByserialnumber(EYB.Web.SerialNumber.UpdateByserialnumberRequest request) {
            return base.Channel.UpdateByserialnumber(request);
        }
        
        public int UpdateByserialnumber(string serialnumber, string MachineNumber) {
            EYB.Web.SerialNumber.UpdateByserialnumberRequest inValue = new EYB.Web.SerialNumber.UpdateByserialnumberRequest();
            inValue.Body = new EYB.Web.SerialNumber.UpdateByserialnumberRequestBody();
            inValue.Body.serialnumber = serialnumber;
            inValue.Body.MachineNumber = MachineNumber;
            EYB.Web.SerialNumber.UpdateByserialnumberResponse retVal = ((EYB.Web.SerialNumber.SerialNumberSoap)(this)).UpdateByserialnumber(inValue);
            return retVal.Body.UpdateByserialnumberResult;
        }
        
        public double GetVersion(int type) {
            return base.Channel.GetVersion(type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EYB.Web.SerialNumber.AddAppStatisticsResponse EYB.Web.SerialNumber.SerialNumberSoap.AddAppStatistics(EYB.Web.SerialNumber.AddAppStatisticsRequest request) {
            return base.Channel.AddAppStatistics(request);
        }
        
        public int AddAppStatistics(string ip, string IPAddress, System.DateTime CreateTime) {
            EYB.Web.SerialNumber.AddAppStatisticsRequest inValue = new EYB.Web.SerialNumber.AddAppStatisticsRequest();
            inValue.Body = new EYB.Web.SerialNumber.AddAppStatisticsRequestBody();
            inValue.Body.ip = ip;
            inValue.Body.IPAddress = IPAddress;
            inValue.Body.CreateTime = CreateTime;
            EYB.Web.SerialNumber.AddAppStatisticsResponse retVal = ((EYB.Web.SerialNumber.SerialNumberSoap)(this)).AddAppStatistics(inValue);
            return retVal.Body.AddAppStatisticsResult;
        }
    }
}
